spring.application.name=backend-management
spring.datasource.url=jdbc:postgresql://localhost:5450/practice_management
spring.datasource.username=practice_user
spring.datasource.password=practice_pass
spring.jpa.hibernate.ddl-auto=update